spring:
  cloud:
    stream:
      bindings:
        readChannel01-in-0:
          destination: channel01
        readChannel01-out-0:
          destination: TRANSACTIONS-TOPIC
          
management:
  endpoints:
    web:
      exposure:
        include: health,info
